# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20190412_2030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='tb_areas',
        ),
    ]
